/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Fuentes.Fuentes;
import Modelo.ArkanoidModel;
import java.awt.Color;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JComboBox;

/**
 *
 * @author Carlos
 */
public class Opciones1 extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Opciones1(ArkanoidModel m) {
        this.model = m;
        initComponents();
        Menu.setContentAreaFilled(false);
        Menu.setBorderPainted(false);
        forma3.setContentAreaFilled(false);
        forma3.setBorderPainted(false);
        forma2.setContentAreaFilled(false);
        forma2.setBorderPainted(false);
        forma1.setContentAreaFilled(false);
        forma1.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Colores = new javax.swing.JLabel();
        rojo = new javax.swing.JButton();
        Rosa = new javax.swing.JButton();
        Morado = new javax.swing.JButton();
        verde = new javax.swing.JButton();
        azul = new javax.swing.JButton();
        Formas = new javax.swing.JLabel();
        forma1 = new javax.swing.JButton();
        forma2 = new javax.swing.JButton();
        forma3 = new javax.swing.JButton();
        Indioma = new javax.swing.JLabel();
        IdiomaSelector = new javax.swing.JComboBox<>();
        Dificultad = new javax.swing.JLabel();
        DificultadSelector = new javax.swing.JComboBox<>();
        Sonido = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        General = new javax.swing.JLabel();
        Juego = new javax.swing.JLabel();
        Música = new javax.swing.JLabel();
        OpcionesText = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Colores.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,12));
        Colores.setText(this.model.messages.getString("Colores"));
        jPanel2.add(Colores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 80, 20));

        rojo.setBackground(Color.RED);
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        jPanel2.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 30, 20));

        Rosa.setBackground(Color.PINK);
        Rosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RosaActionPerformed(evt);
            }
        });
        jPanel2.add(Rosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 30, 20));

        Morado.setBackground(Color.ORANGE);
        Morado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoradoActionPerformed(evt);
            }
        });
        jPanel2.add(Morado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 30, 20));

        verde.setBackground(Color.GREEN);
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        jPanel2.add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 30, 20));

        azul.setBackground(Color.BLUE);
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        jPanel2.add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 30, 20));

        Formas.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,12));
        Formas.setText(this.model.messages.getString("Forma"));
        jPanel2.add(Formas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 80, 20));

        forma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lanzadera.png")));
        forma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forma1ActionPerformed(evt);
            }
        });
        jPanel2.add(forma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 30, 20));

        forma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alien.png")));
        forma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forma2ActionPerformed(evt);
            }
        });
        jPanel2.add(forma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 30, 20));

        forma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ovni-volando.png")));
        forma3.setBackground(new java.awt.Color(255, 0, 0));
        forma3.setForeground(new java.awt.Color(240, 0, 0));
        forma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forma3ActionPerformed(evt);
            }
        });
        jPanel2.add(forma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 30, 20));

        Indioma.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,12));
        Indioma.setText(this.model.messages.getString("Idioma"));
        jPanel2.add(Indioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 80, 20));

        IdiomaSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Alemán", "Francés" }));
        IdiomaSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaSelectorActionPerformed(evt);
            }
        });
        jPanel2.add(IdiomaSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, 20));

        Dificultad.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,12));
        Dificultad.setText(this.model.messages.getString("Dificultad"));
        jPanel2.add(Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 80, 20));

        DificultadSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil", "Extremo" }));
        DificultadSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DificultadSelectorActionPerformed(evt);
            }
        });
        jPanel2.add(DificultadSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 160, 20));

        Sonido.setText(this.model.messages.getString("Juego"));
        jPanel2.add(Sonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 50, 20));
        jPanel2.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel2.add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        General.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,12));
        General.setText(this.model.messages.getString("Sonido"));
        jPanel2.add(General, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, 20));

        Juego.setText(this.model.messages.getString("General"));
        jPanel2.add(Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 50, 20));

        Música.setText(this.model.messages.getString("Musica"));
        jPanel2.add(Música, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 40, 20));

        OpcionesText.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,40));
        OpcionesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OpcionesText.setText(this.model.messages.getString("Opciones"));
        jPanel2.add(OpcionesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 370, 100));

        Menu.setBackground(new java.awt.Color(255, 0, 0));
        Menu.setForeground(new java.awt.Color(240, 0, 0));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lanzamiento-de-cohete-espacial (1) (1).png"))); // NOI18N
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Opciones.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 450, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borde2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 450, 700));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2_1.png")));
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IdiomaSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaSelectorActionPerformed
   
    }//GEN-LAST:event_IdiomaSelectorActionPerformed

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
        this.model.color = 1;
    }//GEN-LAST:event_rojoActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        this.model.color = 2;
    }//GEN-LAST:event_azulActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
        this.model.color = 3;
    }//GEN-LAST:event_verdeActionPerformed

    private void MoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoradoActionPerformed
        this.model.color = 4;
    }//GEN-LAST:event_MoradoActionPerformed

    private void RosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RosaActionPerformed
        this.model.color = 5;
    }//GEN-LAST:event_RosaActionPerformed

    private void forma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma1ActionPerformed
        this.model.forma = 1;
    }//GEN-LAST:event_forma1ActionPerformed

    private void forma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma2ActionPerformed
        this.model.forma = 2;
    }//GEN-LAST:event_forma2ActionPerformed

    private void forma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forma3ActionPerformed
        this.model.forma = 0;
    }//GEN-LAST:event_forma3ActionPerformed

    private void DificultadSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DificultadSelectorActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        String selected = (String) comboBox.getSelectedItem();

        switch (selected) {
            case "Facil":
                this.model.WAIT_TIME = 1000 / model.FPS;
                break;
            case "Medio":
                this.model.WAIT_TIME = 750 / model.FPS;
                break;
            case "Dificil":
                this.model.WAIT_TIME = 500 / model.FPS;
                break;
            case "Extremo":
                this.model.WAIT_TIME = 250 / model.FPS;
                break;
        }
    }//GEN-LAST:event_DificultadSelectorActionPerformed
    
    
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {
        int volumenMusica = jSlider1.getValue();
        this.model.setVolumenMusica(volumenMusica);
    }

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {
        int volumenSonido = jSlider2.getValue();
        this.model.setVolumenSonido(volumenSonido);
    }

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {
        int volumenGeneral = jSlider3.getValue();
        this.model.setVolumenGeneral(volumenGeneral);
    }
    public void actualizaIdioma(){
        OpcionesText.setText(this.model.messages.getString("Opciones"));
        Colores.setText(this.model.messages.getString("Colores"));
        Dificultad.setText(this.model.messages.getString("Dificultad"));
        Formas.setText(this.model.messages.getString("Forma"));
        General.setText(this.model.messages.getString("General"));
        Indioma.setText(this.model.messages.getString("Idioma"));
        Juego.setText(this.model.messages.getString("Juego"));
        Sonido.setText(this.model.messages.getString("Sonido"));
        Música.setText(this.model.messages.getString("Musica"));
    }
    
    private ArkanoidModel model;
    private Fuentes tipoFuente = new Fuentes();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Colores;
    private javax.swing.JLabel Dificultad;
    public javax.swing.JComboBox<String> DificultadSelector;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Formas;
    private javax.swing.JLabel General;
    public javax.swing.JComboBox<String> IdiomaSelector;
    private javax.swing.JLabel Indioma;
    private javax.swing.JLabel Juego;
    public javax.swing.JButton Menu;
    public javax.swing.JButton Morado;
    private javax.swing.JLabel Música;
    private javax.swing.JLabel OpcionesText;
    public javax.swing.JButton Rosa;
    private javax.swing.JLabel Sonido;
    public javax.swing.JButton azul;
    public javax.swing.JButton forma1;
    public javax.swing.JButton forma2;
    public javax.swing.JButton forma3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JSlider jSlider1;
    public javax.swing.JSlider jSlider2;
    public javax.swing.JSlider jSlider3;
    public javax.swing.JButton rojo;
    public javax.swing.JButton verde;
    // End of variables declaration//GEN-END:variables

}
