/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Fuentes.Fuentes;
import Modelo.ArkanoidModel;

/**
 *
 * @author Carlos
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal(ArkanoidModel m) {
        this.modelo=m;
        opcionesPanel = new Opciones1(modelo);
        this.opcionesPanel.setVisible(false);
        initComponents();
        Menu.setContentAreaFilled(false);
        Menu.setBorderPainted(false);
       System.out.print(this.modelo.messages.getString("Niveles"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void actualizaIdioma(){
        Niveles.setText(this.modelo.messages.getString("Niveles"));
        Jugar.setText(this.modelo.messages.getString("Jugar"));
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Arkanoid = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        Niveles = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Arkanoid.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,60));
        Arkanoid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Arkanoid.setText("ARKANOID");
        jPanel2.add(Arkanoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 360, 180));

        Jugar.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,30));
        Jugar.setText(this.modelo.messages.getString("Jugar"));
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        jPanel2.add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 300, 70));

        Niveles.setFont(tipoFuente.fuente(tipoFuente.ARK2,0,30));
        Niveles.setText(this.modelo.messages.getString("Niveles"));
        jPanel2.add(Niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 300, 70));

        Menu.setBackground(new java.awt.Color(255, 0, 0));
        Menu.setForeground(new java.awt.Color(240, 0, 0));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu (5).png"))); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2_1.png")));
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugarActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
       setVisible(false);
       
       opcionesPanel.setVisible(true);
       
    }//GEN-LAST:event_MenuActionPerformed

private Fuentes tipoFuente = new Fuentes();
private ArkanoidModel modelo;
private Opciones1 opcionesPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arkanoid;
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton Jugar;
    public javax.swing.JButton Menu;
    public javax.swing.JButton Niveles;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
